Remove tarampampam packages
avto-dev/firebase-notifications-laravel pull request #15
Opened 2021-04-02 07:15 UTC by malyg1n

## Description

Removed `tarampampam/wrappers-php package`

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in `CHANGELOG.md` file

## Unreleased

### Removed

- Package `tarampampam/wrappers-php`

2021-04-05 08:22 UTC, eldario requested changes

2021-04-05 08:22 UTC, eldario commented on src/ServiceProvider.php
> +            $credentials = (array) \json_decode((string) \file_get_contents($credentials_path), true);
```
$credentials = (array) \json_decode((string) \file_get_contents($credentials_path), true, 512, JSON_THROW_ON_ERROR);
```

2021-04-05 08:22 UTC, eldario commented on src/ServiceProvider.php
> -     * @throws JsonEncodeDecodeException If config file with credentials has invalid JSON format
\JsonException

2021-04-05 08:22 UTC, eldario commented on composer.json
>          "illuminate/notifications": "~6.0 || ~7.0 || ~8.0",
php 7.3

2021-04-05 10:38 UTC, malyg1n commented on src/ServiceProvider.php
> -     * @throws JsonEncodeDecodeException If config file with credentials has invalid JSON format
done

2021-04-05 10:38 UTC, malyg1n commented on composer.json
>          "illuminate/notifications": "~6.0 || ~7.0 || ~8.0",
already

2021-04-06 07:05 UTC, eldario commented on CHANGELOG.md
> +## Unreleased
```suggestion
## v2.5.0
```

2021-04-06 09:29 UTC, eldario approved these changes

2021-04-06 09:30 UTC, merged